import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
// 作成したHeaderコンポーネントをインポート
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        {/* bodyタグの直下にHeaderコンポーネントを配置 */}
        <Header />
        {children}
      </body>
    </html>
  );
}
